<a href="https://colab.research.google.com/github/Fedryus/Ejercicios-IA/blob/master/TFBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Tensor: Vector o matriz
#Flow: Operaciones matematicas

In [0]:
import tensorflow as tf

In [0]:
# CONSTANTE -> tf.constant(valor,tipo,name=)
constante= tf.constant([2.01,3,4],dtype=tf.float32, name="Constante1")

In [5]:
print(constante) #no nos imprime el valor xq estamos definiendo la grafica computacional, no tiene todavia los valores definidos

Tensor("Constante1_1:0", shape=(3,), dtype=float32)


In [0]:
# PLACEHOLDER -> tf.placeholder() 
#Variable vacia al inicio pero que se va llenando a medida que avanzamos. Se usa para los input de data
apartado= tf.placeholder(tf.float32, name= "Apartado1")

In [8]:
print(apartado) #No imprime nada xq otra vez solo estamos definiendo la grafica computacional

Tensor("Apartado1:0", dtype=float32)


In [0]:
# VARIABLE -> tf.Variable()
var= tf.Variable(3,dtype=tf.float32,name="variable1")

In [0]:
matriz= tf.zeros([3,4], tf.int32, name="matriz") #Creacion de una matriz

In [13]:
print(matriz) #No nos da nada como el resto

Tensor("matriz:0", shape=(3, 4), dtype=int32)


In [0]:
#Ahora con todo esto de arriba ya tenemos definida nuestra Grafica Computacional
#GRAFICA COMPUTACIONAL: Planos de nuestro codigo

#Para poder empezar a usar debemos correr una sesion:

In [0]:
#Inicializar variables
inicializar= tf.global_variables_initializer()

In [0]:
session= tf.Session() #Variable que se va a encargar de correr toda la Graf. comp.


In [0]:
session.run(inicializar) #Una vez corro esto todas las variables y const ahora si tienen un valor asignado

In [24]:
print(session.run(matriz))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [0]:
multiplicar= apartado*constante #placeholder*const

In [26]:
print(session.run(multiplicar,feed_dict={apartado:[[15,10,5]]}))

[[30.15 30.   20.  ]]


In [34]:
#Multiplicacion de matrices->necesita (M,N)x(N,M)=(M,M)
a= tf.placeholder(tf.float32,shape=[2,2])
b= tf.placeholder(tf.float32,shape=[2,3])
mult=tf.matmul(a,b)
init= tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(mult,feed_dict={a:[[1,2],[2,2]],b:[[12,21,4],[3,2,4]]}))

[[18. 25. 12.]
 [30. 46. 16.]]


In [37]:
#Multiplicacion de vectores
c= tf.placeholder(tf.float32,shape=[3])
d= tf.placeholder(tf.float32,shape=[3])
punto=tf.tensordot(c,d,1) #multiplicacion punto

init= tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(punto,feed_dict={c:[1,2,3],d:[3,2,1]}))


10.0
